/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'title' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'synopsis' : string,
  'projectId' : ProjectId,
}
export type BookId = bigint;
export interface Chapter {
  'title' : string,
  'createdAt' : Time,
  'bookId' : BookId,
  'updatedAt' : Time,
  'synopsis' : string,
  'hasCover' : boolean,
  'orderIndex' : bigint,
}
export type ChapterId = bigint;
export interface Character {
  'portraitBlob' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : Time,
  'powerDescription' : string,
  'projectId' : ProjectId,
  'reformedPowerDescription' : string,
  'appearanceDescription' : string,
}
export interface CoverReference {
  'createdAt' : Time,
  'description' : string,
  'bookId' : [] | [BookId],
  'chapterId' : [] | [ChapterId],
  'blobId' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export type Id = bigint;
export interface Panel {
  'content' : string,
  'createdAt' : Time,
  'description' : string,
  'chapterId' : ChapterId,
  'layoutId' : bigint,
  'updatedAt' : Time,
  'orderIndex' : bigint,
}
export interface Project {
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
}
export type ProjectId = bigint;
export interface Suggestion {
  'status' : string,
  'suggestionText' : string,
  'createdAt' : Time,
  'projectId' : ProjectId,
  'targetType' : string,
  'targetId' : Id,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBook' : ActorMethod<[Book], Id>,
  'createChapter' : ActorMethod<[Chapter], Id>,
  'createCharacter' : ActorMethod<[Character], Id>,
  'createCoverReference' : ActorMethod<[CoverReference], Id>,
  'createPanel' : ActorMethod<[Panel], Id>,
  'createProject' : ActorMethod<[string, string], Id>,
  'createSuggestion' : ActorMethod<[Suggestion], Id>,
  'deleteBook' : ActorMethod<[Id], undefined>,
  'deleteChapter' : ActorMethod<[Id], undefined>,
  'deleteCharacter' : ActorMethod<[Id], undefined>,
  'deleteCoverReference' : ActorMethod<[Id], undefined>,
  'deletePanel' : ActorMethod<[Id], undefined>,
  'deleteProject' : ActorMethod<[Id], undefined>,
  'deleteSuggestion' : ActorMethod<[Id], undefined>,
  'generateGeminiCompletion' : ActorMethod<[string, string], string>,
  'generateGeminiCompletionStreaming' : ActorMethod<[string, string], string>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getBook' : ActorMethod<[Id], Book>,
  'getBooksForProject' : ActorMethod<[ProjectId], Array<Book>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapter' : ActorMethod<[Id], Chapter>,
  'getChaptersForBook' : ActorMethod<[BookId], Array<Chapter>>,
  'getCharacter' : ActorMethod<[Id], Character>,
  'getCharactersForProject' : ActorMethod<[ProjectId], Array<Character>>,
  'getCoverReference' : ActorMethod<[Id], CoverReference>,
  'getCoverReferencesForBook' : ActorMethod<[BookId], Array<CoverReference>>,
  'getPanel' : ActorMethod<[Id], Panel>,
  'getPanelsForChapter' : ActorMethod<[ChapterId], Array<Panel>>,
  'getProject' : ActorMethod<[Id], Project>,
  'getSuggestion' : ActorMethod<[Id], Suggestion>,
  'getSuggestionsForProject' : ActorMethod<[ProjectId], Array<Suggestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBook' : ActorMethod<[Id, Book], undefined>,
  'updateChapter' : ActorMethod<[Id, Chapter], undefined>,
  'updateCharacter' : ActorMethod<[Id, Character], undefined>,
  'updatePanel' : ActorMethod<[Id, Panel], undefined>,
  'updateProject' : ActorMethod<[Id, Project], undefined>,
  'updateSuggestionStatus' : ActorMethod<[Id, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];