/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ProjectId = IDL.Nat;
export const Book = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'synopsis' : IDL.Text,
  'projectId' : ProjectId,
});
export const Id = IDL.Nat;
export const BookId = IDL.Nat;
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Time,
  'bookId' : BookId,
  'updatedAt' : Time,
  'synopsis' : IDL.Text,
  'hasCover' : IDL.Bool,
  'orderIndex' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Character = IDL.Record({
  'portraitBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : Time,
  'powerDescription' : IDL.Text,
  'projectId' : ProjectId,
  'reformedPowerDescription' : IDL.Text,
  'appearanceDescription' : IDL.Text,
});
export const ChapterId = IDL.Nat;
export const CoverReference = IDL.Record({
  'createdAt' : Time,
  'description' : IDL.Text,
  'bookId' : IDL.Opt(BookId),
  'chapterId' : IDL.Opt(ChapterId),
  'blobId' : ExternalBlob,
});
export const Panel = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'chapterId' : ChapterId,
  'layoutId' : IDL.Nat,
  'updatedAt' : Time,
  'orderIndex' : IDL.Nat,
});
export const Suggestion = IDL.Record({
  'status' : IDL.Text,
  'suggestionText' : IDL.Text,
  'createdAt' : Time,
  'projectId' : ProjectId,
  'targetType' : IDL.Text,
  'targetId' : Id,
});
export const Project = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBook' : IDL.Func([Book], [Id], []),
  'createChapter' : IDL.Func([Chapter], [Id], []),
  'createCharacter' : IDL.Func([Character], [Id], []),
  'createCoverReference' : IDL.Func([CoverReference], [Id], []),
  'createPanel' : IDL.Func([Panel], [Id], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
  'createSuggestion' : IDL.Func([Suggestion], [Id], []),
  'deleteBook' : IDL.Func([Id], [], []),
  'deleteChapter' : IDL.Func([Id], [], []),
  'deleteCharacter' : IDL.Func([Id], [], []),
  'deleteCoverReference' : IDL.Func([Id], [], []),
  'deletePanel' : IDL.Func([Id], [], []),
  'deleteProject' : IDL.Func([Id], [], []),
  'deleteSuggestion' : IDL.Func([Id], [], []),
  'generateGeminiCompletion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'generateGeminiCompletionStreaming' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllProjects' : IDL.Func([], [IDL.Vec(IDL.Tuple(Id, Project))], ['query']),
  'getBook' : IDL.Func([Id], [Book], ['query']),
  'getBooksForProject' : IDL.Func([ProjectId], [IDL.Vec(IDL.Tuple(Id, Book))], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([Id], [Chapter], ['query']),
  'getChaptersForBook' : IDL.Func([BookId], [IDL.Vec(IDL.Tuple(Id, Chapter))], ['query']),
  'getCharacter' : IDL.Func([Id], [Character], ['query']),
  'getCharactersForProject' : IDL.Func(
      [ProjectId],
      [IDL.Vec(IDL.Tuple(Id, Character))],
      ['query'],
    ),
  'getCoverReference' : IDL.Func([Id], [CoverReference], ['query']),
  'getCoverReferencesForBook' : IDL.Func(
      [BookId],
      [IDL.Vec(IDL.Tuple(Id, CoverReference))],
      ['query'],
    ),
  'getPanel' : IDL.Func([Id], [Panel], ['query']),
  'getPanelsForChapter' : IDL.Func([ChapterId], [IDL.Vec(IDL.Tuple(Id, Panel))], ['query']),
  'getProject' : IDL.Func([Id], [Project], ['query']),
  'getSuggestion' : IDL.Func([Id], [Suggestion], ['query']),
  'getSuggestionsForProject' : IDL.Func(
      [ProjectId],
      [IDL.Vec(IDL.Tuple(Id, Suggestion))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBook' : IDL.Func([Id, Book], [], []),
  'updateChapter' : IDL.Func([Id, Chapter], [], []),
  'updateCharacter' : IDL.Func([Id, Character], [], []),
  'updatePanel' : IDL.Func([Id, Panel], [], []),
  'updateProject' : IDL.Func([Id, Project], [], []),
  'updateSuggestionStatus' : IDL.Func([Id, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProjectId = IDL.Nat;
  const Book = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'synopsis' : IDL.Text,
    'projectId' : ProjectId,
  });
  const Id = IDL.Nat;
  const BookId = IDL.Nat;
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Time,
    'bookId' : BookId,
    'updatedAt' : Time,
    'synopsis' : IDL.Text,
    'hasCover' : IDL.Bool,
    'orderIndex' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Character = IDL.Record({
    'portraitBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : Time,
    'powerDescription' : IDL.Text,
    'projectId' : ProjectId,
    'reformedPowerDescription' : IDL.Text,
    'appearanceDescription' : IDL.Text,
  });
  const ChapterId = IDL.Nat;
  const CoverReference = IDL.Record({
    'createdAt' : Time,
    'description' : IDL.Text,
    'bookId' : IDL.Opt(BookId),
    'chapterId' : IDL.Opt(ChapterId),
    'blobId' : ExternalBlob,
  });
  const Panel = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'chapterId' : ChapterId,
    'layoutId' : IDL.Nat,
    'updatedAt' : Time,
    'orderIndex' : IDL.Nat,
  });
  const Suggestion = IDL.Record({
    'status' : IDL.Text,
    'suggestionText' : IDL.Text,
    'createdAt' : Time,
    'projectId' : ProjectId,
    'targetType' : IDL.Text,
    'targetId' : Id,
  });
  const Project = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBook' : IDL.Func([Book], [Id], []),
    'createChapter' : IDL.Func([Chapter], [Id], []),
    'createCharacter' : IDL.Func([Character], [Id], []),
    'createCoverReference' : IDL.Func([CoverReference], [Id], []),
    'createPanel' : IDL.Func([Panel], [Id], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
    'createSuggestion' : IDL.Func([Suggestion], [Id], []),
    'deleteBook' : IDL.Func([Id], [], []),
    'deleteChapter' : IDL.Func([Id], [], []),
    'deleteCharacter' : IDL.Func([Id], [], []),
    'deleteCoverReference' : IDL.Func([Id], [], []),
    'deletePanel' : IDL.Func([Id], [], []),
    'deleteProject' : IDL.Func([Id], [], []),
    'deleteSuggestion' : IDL.Func([Id], [], []),
    'generateGeminiCompletion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'generateGeminiCompletionStreaming' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(IDL.Tuple(Id, Project))], ['query']),
    'getBook' : IDL.Func([Id], [Book], ['query']),
    'getBooksForProject' : IDL.Func([ProjectId], [IDL.Vec(IDL.Tuple(Id, Book))], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([Id], [Chapter], ['query']),
    'getChaptersForBook' : IDL.Func([BookId], [IDL.Vec(IDL.Tuple(Id, Chapter))], ['query']),
    'getCharacter' : IDL.Func([Id], [Character], ['query']),
    'getCharactersForProject' : IDL.Func(
        [ProjectId],
        [IDL.Vec(IDL.Tuple(Id, Character))],
        ['query'],
      ),
    'getCoverReference' : IDL.Func([Id], [CoverReference], ['query']),
    'getCoverReferencesForBook' : IDL.Func(
        [BookId],
        [IDL.Vec(IDL.Tuple(Id, CoverReference))],
        ['query'],
      ),
    'getPanel' : IDL.Func([Id], [Panel], ['query']),
    'getPanelsForChapter' : IDL.Func([ChapterId], [IDL.Vec(IDL.Tuple(Id, Panel))], ['query']),
    'getProject' : IDL.Func([Id], [Project], ['query']),
    'getSuggestion' : IDL.Func([Id], [Suggestion], ['query']),
    'getSuggestionsForProject' : IDL.Func(
        [ProjectId],
        [IDL.Vec(IDL.Tuple(Id, Suggestion))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBook' : IDL.Func([Id, Book], [], []),
    'updateChapter' : IDL.Func([Id, Chapter], [], []),
    'updateCharacter' : IDL.Func([Id, Character], [], []),
    'updatePanel' : IDL.Func([Id, Panel], [], []),
    'updateProject' : IDL.Func([Id, Project], [], []),
    'updateSuggestionStatus' : IDL.Func([Id, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };