/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Panel {
    content: string;
    createdAt: Time;
    description: string;
    chapterId: ChapterId;
    layoutId: bigint;
    updatedAt: Time;
    orderIndex: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Suggestion {
    status: string;
    suggestionText: string;
    createdAt: Time;
    projectId: ProjectId;
    targetType: string;
    targetId: Id;
}
export interface CoverReference {
    createdAt: Time;
    description: string;
    bookId?: BookId;
    chapterId?: ChapterId;
    blobId: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Character {
    portraitBlob?: ExternalBlob;
    name: string;
    createdAt: Time;
    powerDescription: string;
    projectId: ProjectId;
    reformedPowerDescription: string;
    appearanceDescription: string;
}
export interface Chapter {
    title: string;
    createdAt: Time;
    bookId: BookId;
    updatedAt: Time;
    synopsis: string;
    hasCover: boolean;
    orderIndex: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type ChapterId = bigint;
export interface Book {
    title: string;
    createdAt: Time;
    updatedAt: Time;
    synopsis: string;
    projectId: ProjectId;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type Id = bigint;
export type ProjectId = bigint;
export type BookId = bigint;
export interface Project {
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBook(book: Book): Promise<Id>;
    createChapter(chapter: Chapter): Promise<Id>;
    createCharacter(character: Character): Promise<Id>;
    createCoverReference(coverReference: CoverReference): Promise<Id>;
    createPanel(panel: Panel): Promise<Id>;
    createProject(name: string, description: string): Promise<Id>;
    createSuggestion(suggestion: Suggestion): Promise<Id>;
    deleteBook(id: Id): Promise<void>;
    deleteChapter(id: Id): Promise<void>;
    deleteCharacter(id: Id): Promise<void>;
    deleteCoverReference(id: Id): Promise<void>;
    deletePanel(id: Id): Promise<void>;
    deleteProject(id: Id): Promise<void>;
    deleteSuggestion(id: Id): Promise<void>;
    generateGeminiCompletion(apiKey: string, body: string): Promise<string>;
    generateGeminiCompletionStreaming(apiKey: string, body: string): Promise<string>;
    getAllProjects(): Promise<Array<Project>>;
    getBook(id: Id): Promise<Book>;
    getBooksForProject(projectId: ProjectId): Promise<Array<Book>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChapter(id: Id): Promise<Chapter>;
    getChaptersForBook(bookId: BookId): Promise<Array<Chapter>>;
    getCharacter(id: Id): Promise<Character>;
    getCharactersForProject(projectId: ProjectId): Promise<Array<Character>>;
    getCoverReference(id: Id): Promise<CoverReference>;
    getCoverReferencesForBook(bookId: BookId): Promise<Array<CoverReference>>;
    getPanel(id: Id): Promise<Panel>;
    getPanelsForChapter(chapterId: ChapterId): Promise<Array<Panel>>;
    getProject(id: Id): Promise<Project>;
    getSuggestion(id: Id): Promise<Suggestion>;
    getSuggestionsForProject(projectId: ProjectId): Promise<Array<Suggestion>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBook(id: Id, book: Book): Promise<void>;
    updateChapter(id: Id, chapter: Chapter): Promise<void>;
    updateCharacter(id: Id, character: Character): Promise<void>;
    updatePanel(id: Id, panel: Panel): Promise<void>;
    updateProject(id: Id, project: Project): Promise<void>;
    updateSuggestionStatus(id: Id, status: string): Promise<void>;
}
import type { BookId as _BookId, ChapterId as _ChapterId, Character as _Character, CoverReference as _CoverReference, ExternalBlob as _ExternalBlob, ProjectId as _ProjectId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBook(arg0: Book): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBook(arg0);
            return result;
        }
    }
    async createChapter(arg0: Chapter): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChapter(arg0);
            return result;
        }
    }
    async createCharacter(arg0: Character): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createCharacter(await to_candid_Character_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCharacter(await to_candid_Character_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCoverReference(arg0: CoverReference): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoverReference(await to_candid_CoverReference_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoverReference(await to_candid_CoverReference_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPanel(arg0: Panel): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createPanel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPanel(arg0);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createSuggestion(arg0: Suggestion): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSuggestion(arg0);
            return result;
        }
    }
    async deleteBook(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async deleteChapter(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteCharacter(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharacter(arg0);
            return result;
        }
    }
    async deleteCoverReference(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoverReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoverReference(arg0);
            return result;
        }
    }
    async deletePanel(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePanel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePanel(arg0);
            return result;
        }
    }
    async deleteProject(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteSuggestion(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSuggestion(arg0);
            return result;
        }
    }
    async generateGeminiCompletion(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateGeminiCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateGeminiCompletion(arg0, arg1);
            return result;
        }
    }
    async generateGeminiCompletionStreaming(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateGeminiCompletionStreaming(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateGeminiCompletionStreaming(arg0, arg1);
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getBook(arg0: Id): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return result;
        }
    }
    async getBooksForProject(arg0: ProjectId): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooksForProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooksForProject(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapter(arg0: Id): Promise<Chapter> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return result;
        }
    }
    async getChaptersForBook(arg0: BookId): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChaptersForBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChaptersForBook(arg0);
            return result;
        }
    }
    async getCharacter(arg0: Id): Promise<Character> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacter(arg0);
                return from_candid_Character_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacter(arg0);
            return from_candid_Character_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharactersForProject(arg0: ProjectId): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharactersForProject(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharactersForProject(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoverReference(arg0: Id): Promise<CoverReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoverReference(arg0);
                return from_candid_CoverReference_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoverReference(arg0);
            return from_candid_CoverReference_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoverReferencesForBook(arg0: BookId): Promise<Array<CoverReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoverReferencesForBook(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoverReferencesForBook(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPanel(arg0: Id): Promise<Panel> {
        if (this.processError) {
            try {
                const result = await this.actor.getPanel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPanel(arg0);
            return result;
        }
    }
    async getPanelsForChapter(arg0: ChapterId): Promise<Array<Panel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPanelsForChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPanelsForChapter(arg0);
            return result;
        }
    }
    async getProject(arg0: Id): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return result;
        }
    }
    async getSuggestion(arg0: Id): Promise<Suggestion> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestion(arg0);
            return result;
        }
    }
    async getSuggestionsForProject(arg0: ProjectId): Promise<Array<Suggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestionsForProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestionsForProject(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBook(arg0: Id, arg1: Book): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, arg1);
            return result;
        }
    }
    async updateChapter(arg0: Id, arg1: Chapter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1);
            return result;
        }
    }
    async updateCharacter(arg0: Id, arg1: Character): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharacter(arg0, await to_candid_Character_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharacter(arg0, await to_candid_Character_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePanel(arg0: Id, arg1: Panel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePanel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePanel(arg0, arg1);
            return result;
        }
    }
    async updateProject(arg0: Id, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1);
            return result;
        }
    }
    async updateSuggestionStatus(arg0: Id, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSuggestionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSuggestionStatus(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_Character_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Character): Promise<Character> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_CoverReference_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoverReference): Promise<CoverReference> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookId]): BookId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChapterId]): ChapterId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portraitBlob: [] | [_ExternalBlob];
    name: string;
    createdAt: _Time;
    powerDescription: string;
    projectId: _ProjectId;
    reformedPowerDescription: string;
    appearanceDescription: string;
}): Promise<{
    portraitBlob?: ExternalBlob;
    name: string;
    createdAt: Time;
    powerDescription: string;
    projectId: ProjectId;
    reformedPowerDescription: string;
    appearanceDescription: string;
}> {
    return {
        portraitBlob: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.portraitBlob)),
        name: value.name,
        createdAt: value.createdAt,
        powerDescription: value.powerDescription,
        projectId: value.projectId,
        reformedPowerDescription: value.reformedPowerDescription,
        appearanceDescription: value.appearanceDescription
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Time;
    description: string;
    bookId: [] | [_BookId];
    chapterId: [] | [_ChapterId];
    blobId: _ExternalBlob;
}): Promise<{
    createdAt: Time;
    description: string;
    bookId?: BookId;
    chapterId?: ChapterId;
    blobId: ExternalBlob;
}> {
    return {
        createdAt: value.createdAt,
        description: value.description,
        bookId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.bookId)),
        chapterId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.chapterId)),
        blobId: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.blobId)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Character>): Promise<Array<Character>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Character_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoverReference>): Promise<Array<CoverReference>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CoverReference_n23(_uploadFile, _downloadFile, x)));
}
async function to_candid_Character_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Character): Promise<_Character> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_CoverReference_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoverReference): Promise<_CoverReference> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portraitBlob?: ExternalBlob;
    name: string;
    createdAt: Time;
    powerDescription: string;
    projectId: ProjectId;
    reformedPowerDescription: string;
    appearanceDescription: string;
}): Promise<{
    portraitBlob: [] | [_ExternalBlob];
    name: string;
    createdAt: _Time;
    powerDescription: string;
    projectId: _ProjectId;
    reformedPowerDescription: string;
    appearanceDescription: string;
}> {
    return {
        portraitBlob: value.portraitBlob ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.portraitBlob)) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        powerDescription: value.powerDescription,
        projectId: value.projectId,
        reformedPowerDescription: value.reformedPowerDescription,
        appearanceDescription: value.appearanceDescription
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: Time;
    description: string;
    bookId?: BookId;
    chapterId?: ChapterId;
    blobId: ExternalBlob;
}): Promise<{
    createdAt: _Time;
    description: string;
    bookId: [] | [_BookId];
    chapterId: [] | [_ChapterId];
    blobId: _ExternalBlob;
}> {
    return {
        createdAt: value.createdAt,
        description: value.description,
        bookId: value.bookId ? candid_some(value.bookId) : candid_none(),
        chapterId: value.chapterId ? candid_some(value.chapterId) : candid_none(),
        blobId: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.blobId)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
